### ISSUE TITLE
Issue with the library due to the commented out code in the decimal to hex conversion

### ISSUE THREAD

**Issue by WajdiMuh** [Bayramito/react-native-colorpicker#1]
I have tried to use your library and found out that it doesnt display the coorrect hex values but when i uncommented out the code it was fixed 
specifically this code
`    // if (number < 0) {
    //   number = 0xffffffff + number + 1;
    // }`

**Comment by WajdiMuh** [comment]
the issue still exists with the latest npm package version 1.0.23 although it has been fixed here

**Comment by Bayramito** [comment]
it should be gone now
